### ISSUE TITLE
dopo salvataggio lista azioni

### ISSUE THREAD

**Issue by andreamapelli2** [cerelli/informacrm#17]
Lista azioni: io sono andrea, visualizzo le azioni di marco e ne edito una. Dopo aver salvato mi ritorna l'elenco delle azioni di andrea, mentre dovrei vedere ancora quelle di marco.
Anche se edito una mia azione poi mi perde i filtri immessi prima della modifica (o semplicemente del salvataggio)

**Comment by cerelli** [comment]
Si, al momento funziona così. Non salva i filtri.
