### ISSUE TITLE
Errore Nuovo indirizzo

### ISSUE THREAD

**Issue by andreamapelli2** [cerelli/informacrm#22]
Facendo salva nella creazione di un nuovo indirizzo da errore:
500
It's not you, it's me.
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'address_types_id' in 'field list' (SQL: update `addresses` set `address_types_id` = , `updated_at` = 2018-04-03 08:44:30 where `id` = 6)

In realtà l'indirizzo viene creato. Poi eliminandolo mi chiede di cliccare due volte poi esce un errore e subito dopo che è stato eliminato correttamente.

**Comment by cerelli** [comment]
Sistemato nel prossimo rilascio 0.4.5
